import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserModeProvider } from "@/context/modeContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cognimed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <UserModeProvider>
          {children}
       </UserModeProvider>
       
        </body>
    </html>
  );
}
